# 분석용 기초

## Numpy 계속

In [1]:
# NumPy 로드
import numpy as np

In [8]:
nb = np.array([1,2,3,4,5,6])

In [9]:
nb

array([1, 2, 3, 4, 5, 6])

In [11]:
# 정규화
nd = np.array([10,20,30])


normalized = (nd - nd.mean())/ nd.std()

normalized

array([-1.22474487,  0.        ,  1.22474487])

In [13]:
scores = np.array([50,80,90,60,30])


scores[scores >= 60]

array([80, 90, 60])

### pandas 
- 엑셀을 코드로 다루는 도구 
- 표 형태의 데이터 처리 가능 
- 데이터분석시 가장 많이 사용되는 라이브러리
  

#### 설치 
- pip install pandas

#### 판다스 기초
- 핵심구조
  - dataframe : 기준, 2차원 배열
  - series : 최소원소, 1차원 배열

In [14]:
# 판다스 라이브러리 로드 
import pandas as pd

In [15]:
# 시리즈 
s1 = pd.Series([10,20,30])
s1

0    10
1    20
2    30
dtype: int64

In [17]:
# 데이터프레임
data = {
    "name" : ['유고', '요미', '철수'],
    "score" : [90,100, 36]
}

data


df = pd.DataFrame(data)
df

  name  score
0   유고     90
1   요미    100
2   철수     36

In [23]:
# csv 읽기

df = pd.read_csv('도서정보.csv', encoding='UTF-8')
df

,번호,서명,저자,발행자,발행년,청구기호,자료실
0,1,해럴드와 마법 크레용 [비디오녹화자료],카를로스 살다냐 감독,소니 픽쳐스 홈엔터테인먼트 [공급],2025,DVD 688.2-2246,[해운대인문학]디지털자료실
1,2,나처럼 예쁜 여자 [비디오녹화자료],프랑수아 트뤼포 감독,Art Film [수입·제조],2024,DVD 688.2-2247,[해운대인문학]디지털자료실
2,3,조커 [비디오녹화자료] : 폴리 아 되,토드 필립스 감독,해리슨 앤 컴퍼니 [제조·판매],[2025],DVD 688.2-2248,[해운대인문학]디지털자료실
3,4,"신비아파트 고스트볼 ZERO [비디오녹화자료]. 2, 싹트는 울음소리, 뿌리 괴수의 진실",박홍근 총감독,뮤라인 [제작·판매],2025,DVD 688.6-1141-2,[해운대인문학]디지털자료실
4,5,마당을 나온 암탉 [비디오녹화자료],오성윤 감독,미디어포유 [제작·판매],2025,DVD 688.6-335=2,[해운대인문학]디지털자료실
5,6,더 파일럿 [비디오녹화자료] : 드론 어택,폴 듀세 감독,미디어포유 [제작·판매],2025,DVD 688.2-2249,[해운대인문학]디지털자료실
6,7,새터데이 나이트 [비디오녹화자료],제이슨 라이트먼 감독,소니 픽쳐스 홈엔터테인먼트 [공급],2025,DVD 688.2-2250,[해운대인문학]디지털자료실
7,8,구룡성채 [비디오녹화자료] : 무법지대,정바오루이 감독,플레인아카이브 [DVD 제작·판매],[2025],DVD 688.2-2251,[해운대인문학]디지털자료실
8,9,"신비아파트 고스트볼 ZERO [비디오녹화자료]. 3, 수상한 공사장의 비밀",박홍근 총감독,뮤라인 [제작·판매],2025,DVD 688.6-1141-3,[해운대인문학]디지털자료실
9,10,베리 미 트와이스 [비디오녹화자료],스티븐 라모트 감독,미디어포유 [제작],2025,DVD 688.2-2252,[해운대인문학]디지털자료실

In [27]:
# 데이터 확인 - 상위 5개 확인(디폴트값)
df.head()
# 상위 3개 확인
df.head(3)

,번호,서명,저자,발행자,발행년,청구기호,자료실
0,1,해럴드와 마법 크레용 [비디오녹화자료],카를로스 살다냐 감독,소니 픽쳐스 홈엔터테인먼트 [공급],2025,DVD 688.2-2246,[해운대인문학]디지털자료실
1,2,나처럼 예쁜 여자 [비디오녹화자료],프랑수아 트뤼포 감독,Art Film [수입·제조],2024,DVD 688.2-2247,[해운대인문학]디지털자료실
2,3,조커 [비디오녹화자료] : 폴리 아 되,토드 필립스 감독,해리슨 앤 컴퍼니 [제조·판매],[2025],DVD 688.2-2248,[해운대인문학]디지털자료실

In [30]:
# 하위 3개 확인
df.tail(3)

,번호,서명,저자,발행자,발행년,청구기호,자료실
7,8,구룡성채 [비디오녹화자료] : 무법지대,정바오루이 감독,플레인아카이브 [DVD 제작·판매],[2025],DVD 688.2-2251,[해운대인문학]디지털자료실
8,9,"신비아파트 고스트볼 ZERO [비디오녹화자료]. 3, 수상한 공사장의 비밀",박홍근 총감독,뮤라인 [제작·판매],2025,DVD 688.6-1141-3,[해운대인문학]디지털자료실
9,10,베리 미 트와이스 [비디오녹화자료],스티븐 라모트 감독,미디어포유 [제작],2025,DVD 688.2-2252,[해운대인문학]디지털자료실

In [36]:

df = pd.read_excel('sample.xlsx')
df

    이름   국어     영어   수학
0  홍길동   95   98.0   93
1  애슐리  100  100.0  100
2  성명건   90    NaN   70
3  김예성   80   80.0  100

In [39]:
# 새 컬럼 만들기
df['수학1'] = df['수학'] -5
df

    이름   국어     영어   수학  수학1
0  홍길동   95   98.0   93   88
1  애슐리  100  100.0  100   95
2  성명건   90    NaN   70   65
3  김예성   80   80.0  100   95

In [40]:
# 정렬
df.sort_values('수학')

    이름   국어     영어   수학  수학1
2  성명건   90    NaN   70   65
0  홍길동   95   98.0   93   88
1  애슐리  100  100.0  100   95
3  김예성   80   80.0  100   95

In [42]:
# 결측치 처리
# 널 값이 존재한 컬럼을 삭제
df1 = df.dropna()
df1

    이름   국어     영어   수학  수학1
0  홍길동   95   98.0   93   88
1  애슐리  100  100.0  100   95
3  김예성   80   80.0  100   95

In [43]:
# 결측치 메꾸기
df2 = df.fillna(45)
df2

    이름   국어     영어   수학  수학1
0  홍길동   95   98.0   93   88
1  애슐리  100  100.0  100   95
2  성명건   90   45.0   70   65
3  김예성   80   80.0  100   95

In [44]:
#그룹화
df.groupby('수학').count()

     이름  국어  영어  수학1
수학
70    1   1   0    1
93    1   1   1    1
100   2   2   2    2

In [45]:
df[['국어', "영어", "수학"]].fillna(45).groupby('수학').mean()

       국어    영어
수학
70   90.0  45.0
93   95.0  98.0
100  90.0  90.0

### 간단 예제

In [46]:
data = {
    'name' : ['유고', '요미', '철수', '예성'],
    'score':[80,90,70,60] 
}

df = pd.DataFrame(data)
df

  name  score
0   유고     80
1   요미     90
2   철수     70
3   예성     60

In [47]:
# csv로 쓰기
df.to_csv('score.csv', encoding='utf-8')

In [ ]:
df.to_excel('score.xlsx')

#평균이상만 추출
df[df['score'] >= df['score'].mean()]

  name  score
0   유고     80
1   요미     90

In [54]:
#합격 여부
df['result'] = ['pass'if s >= 70 else 'fail' for s in df['score']]
df

  name  score result
0   유고     80   pass
1   요미     90   pass
2   철수     70   pass
3   예성     60   fail